image: docker:19.03.13

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

services:
  - docker:19.03.13-dind

before_script:
  - docker info

stages:
#  - test
  - build

#lint:
#  stage: test
#  image: hadolint/hadolint:latest-debian
#  script:
#    - /bin/hadolint Dockerfile.*

docker_build:
  stage: build
  script:
    - docker build -f Dockerfile.nginx -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
