stages:
  - test
  - build
  - deploy

lint:
  stage: test
  image: hadolint/hadolint:latest-debian
  script:
    - /bin/hadolint Dockerfile.*

docker_build:
  stage: build
  image: docker:latest
  script:
    - docker build -f Dockerfile.nginx -t $CI_REGISTRY_IMAGE:latest .

docker_deploy:
  stage: deploy
  image: docker:latest
  script:
    - docker push $CI_REGISTRY_IMAGE:latest
